### PR TITLE
github actions and adding LRM and Tau-BC to shiny app.

### PR DESCRIPTION
**Pull request by manchen07**
This pull request is for issue #48 #49 and #50. I'm sorry I pushed several commits on setting github actions for R-CMD-check. It should work now.

Still need to add Tau_BC and LRM to the vignettes.

### CODE REVIEW

**Review by jepusto — CHANGES_REQUESTED** [review]
The pkgdown setup looks good to me. 

For checking via github actions, please use `usethis::use_github_action_check_standard()` so that the package gets checked on multiple OS and for multiple versions of R. 

Also please include a step to check unit test coverage with codecov. I added codecov.yml but will need to run `'covr::codecov()'` as a script after running R-CMD-check.

If it's not too much of a pain, could you also please use a separate branch for the shiny app stuff? That way, I can merge the PR for the website and github actions.

**Review by jepusto — CHANGES_REQUESTED** [review]
Please ensure that the following instructions are up-to-date based on the additional features of Tau-BC and LRM:
- `inst/shiny-examples/SCD-effect-sizes/markdown/using_single.md`
- `inst/shiny-examples/SCD-effect-sizes/markdown/using_batch.md`

In the batch calculator, move the `weighting_scheme` radio button to appear above the `b_phase` selector, right after the `b_aggregate` selector`. Alternately, the `weighting_scheme` radio button could appear towards the bottom of the options on the `Estimate` tab.

In the `Syntax for R` tab of the batch calculator, should we try to give the data and results objects names that are adapted based on the input?

**Comment by jepusto** [comment]
I edited the package vignettes and the markdown files describing the technical details of the effect size estimators (including the new ones). Man, could you please make sure that the markdown files for `Tau-BC` and `LRM` are connected up and display in the Shiny app?

**Comment by manchen07** [comment]
Sure! Thanks for the updates.

- -
Man Chen (she/her/hers)
PhD student, Quantitative Methods
Department of Educational Psychology
University of Wisconsin-Madison

________________________________

**Comment by manchen07** [comment]
Just a reminder that this pull request is for issue #40 #48 #49 #50 and #52. Please let me know if I missed anything.

**Review by jepusto — CHANGES_REQUESTED** [review]
Everything looks good, except for one last issue. Right now `SCD_effect_sizes()` checks for whether `shiny` and `ggplot2` are installed. However, the app now uses several further packages that the user will need to ensure are installed. Please make sure that the installation checks catch all packages needed to run the app. See `scdhlm::shine_SCD()` for one approach to streamlining these checks.

**Review by jepusto — APPROVED** [review]

**Review by jepusto — APPROVED** [review]

**Comment by jepusto** [comment]
Closes #40. Closes #48. Closes #49. Closes #50. Closes #52.

**Pull request merged**
