### PR TITLE
Added Kendall rank correlation to Tau_BC().

### PR DESCRIPTION
**Pull request by manchen07**

### CODE REVIEW

**Review by jepusto — CHANGES_REQUESTED** [review]
Thanks for handling this! I've made some further revisions and also renamed the `tarlow` argument as `Kendall`. Please take a look at the following:

* Make sure that the unit tests for `Tau_BC()` all pass. I added one that currently fails because of the handling of the `confidence` argument when `Kendall = TRUE`. 
* Please add shiny app unit tests that check the calculations when `Kendall = TRUE`.
* Revise the `tau-BC.md` in the shiny app to describe the additional option that you added.
* Add an entry to `NEWS` to describe the changes.

**Comment by manchen07** [comment]
> Thanks for handling this! I've made some further revisions and also renamed the `tarlow` argument as `Kendall`. Please take a look at the following:

Thank you for revising the codes for `Tau_BC()`.

> 
> * Make sure that the unit tests for `Tau_BC()` all pass. I added one that currently fails because of the handling of the `confidence` argument when `Kendall = TRUE`.

I'm not sure if I understand this correctly. The standard error for Tau (non-overlap) is different from that for Kendall's rank correlation, so I used `expect_error()`.

> * Please add shiny app unit tests that check the calculations when `Kendall = TRUE`.

I added `Kendall = TRUE` to `check_single()`, `check_batch()`, and `check_load()`and updated the tests. I did not add unit test to check `Kendall = TRUE` for loaded data files. Please let me know if you'd like to add that.

> * Revise the `tau-BC.md` in the shiny app to describe the additional option that you added.

Done. Shall we add the calculation/formula of Kendall's rank correlation as well?

> * Add an entry to `NEWS` to describe the changes.

Done. There is some conflict with master branch regarding NEWS. I'm not sure what's the best way to resolve that without messing things up, so could you please take a look at the conflict?

Let me know if I miss anything or if more changes are needed. Thanks!

**Comment by jepusto** [comment]
For the confidence interval, the issue is that it should only be included in the output when !is.null(confidence). That logic is missing in the condition when Kendall = TRUE.

Please do include the formula for the Kendall rank correlation, and I’ll look it over once you’ve drafted.

**Comment by manchen07** [comment]
> Please do include the formula for the Kendall rank correlation, and I’ll look it over once you’ve drafted.

I've added the formula for the Kendall rank correlation in the Effect-size-definitions.Rmd vignette. I've not added them to Tau-BC.md, which can be updated easily after you look over and revise the vignette.

**Comment by jepusto** [comment]
One issue I didn't notice initially: `Tau_BC()` with `Kendall = TRUE` needs to handle the outcome valence. If improvement = "decrease", then Tau_BC() should give a positive number when there is a reduction in the DV.

**Review by jepusto — APPROVED** [review]

**Review by jepusto — APPROVED** [review]

**Pull request merged**
